### ISSUE TITLE
Does this need a 1.18.2 build?

### ISSUE THREAD

**Issue by Sunconure11** [Tfarcenim/XLPacketsFabric#2]
Was gonna ask, then I saw someone made a similar issue... and then closed it for no reason.

Basically, does this mod already work with 1.18.2, or would a build have to be made with it in mind?

@Tfarcenim

**Comment by Sunconure11** [comment]
Alright, some light testing has proven it works on 1.18.2. It just needs to be marked as such on Curse. Keeping this open for reference until then.

**Comment by netcore10** [comment]
I don't think server is picking up this mod, large packets just boot me off.

**Comment by netcore10** [comment]
> I don't think server is picking up this mod, large packets just boot me off.

I've basically been unable to progress with my community server because of large packets.

**Comment by Sunconure11** [comment]
> > I don't think server is picking up this mod, large packets just boot me off.
> 
> I've basically been unable to progress with my community server because of large packets.

Try this

https://www.curseforge.com/minecraft/mc-mods/connectivity

**Comment by netcore10** [comment]
i tried that sadly, they both don't fix the packet issue, and i've had to post an issue on both.

**Comment by netcore10** [comment]
it was forgero, issue resolved.

**Comment by Tfarcenim** [comment]
1.18.2 now has an official build with 1.19.2 on the way.
